[2024-12-23T05:45:46.061+0700] {processor.py:186} INFO - Started process (PID=1411) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:45:46.063+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T05:45:46.069+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:45:46.067+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:45:46.102+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:45:46.095+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T05:45:46.105+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:45:46.104+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T05:45:46.106+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:45:46.130+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.083 seconds
[2024-12-23T05:53:23.188+0700] {processor.py:186} INFO - Started process (PID=1778) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:53:23.191+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T05:53:23.197+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:53:23.195+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:53:23.240+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:53:23.229+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T05:53:23.244+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:53:23.242+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T05:53:23.246+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:53:23.280+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.111 seconds
[2024-12-23T05:53:45.460+0700] {processor.py:186} INFO - Started process (PID=1836) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:53:45.463+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T05:53:45.472+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:53:45.470+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:53:45.527+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:53:45.515+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T05:53:45.531+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:53:45.529+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T05:53:45.533+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:53:45.567+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.132 seconds
[2024-12-23T05:55:27.402+0700] {processor.py:186} INFO - Started process (PID=2119) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:55:27.404+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T05:55:27.408+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:55:27.407+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:55:27.440+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:55:27.432+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T05:55:27.443+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:55:27.442+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T05:55:27.444+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:55:27.469+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2024-12-23T05:56:58.219+0700] {processor.py:186} INFO - Started process (PID=2299) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:56:58.221+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T05:56:58.227+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:56:58.225+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:56:58.267+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:56:58.260+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T05:56:58.269+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:56:58.268+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T05:56:58.270+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:56:58.301+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2024-12-23T05:58:35.017+0700] {processor.py:186} INFO - Started process (PID=2533) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:58:35.023+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T05:58:35.040+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:58:35.036+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:58:35.103+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:58:35.092+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T05:58:35.107+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:58:35.105+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T05:58:35.108+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:58:35.183+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.190 seconds
[2024-12-23T05:59:23.951+0700] {processor.py:186} INFO - Started process (PID=2645) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:59:23.953+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T05:59:23.960+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:59:23.958+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:59:23.999+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:59:23.991+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T05:59:24.002+0700] {logging_mixin.py:190} INFO - [2024-12-23T05:59:24.000+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T05:59:24.003+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T05:59:24.031+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2024-12-23T06:00:15.305+0700] {processor.py:186} INFO - Started process (PID=2798) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:00:15.308+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:00:15.313+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:00:15.311+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:00:15.355+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:00:15.346+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:00:15.358+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:00:15.357+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:00:15.361+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:00:15.390+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-12-23T06:00:48.109+0700] {processor.py:186} INFO - Started process (PID=2882) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:00:48.111+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:00:48.116+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:00:48.114+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:00:48.154+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:00:48.147+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:00:48.156+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:00:48.156+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:00:48.158+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:00:48.188+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-12-23T06:02:16.595+0700] {processor.py:186} INFO - Started process (PID=3079) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:02:16.598+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:02:16.607+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:02:16.605+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:02:16.666+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:02:16.653+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:02:16.673+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:02:16.670+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:02:16.676+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:02:16.719+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.157 seconds
[2024-12-23T06:04:28.525+0700] {processor.py:186} INFO - Started process (PID=3399) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:04:28.528+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:04:28.534+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:04:28.532+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:04:28.588+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:04:28.579+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:04:28.591+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:04:28.589+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:04:28.593+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:04:28.631+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.131 seconds
[2024-12-23T06:06:29.020+0700] {processor.py:186} INFO - Started process (PID=3684) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:06:29.024+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:06:29.030+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:06:29.028+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:06:29.080+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:06:29.071+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:06:29.083+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:06:29.082+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:06:29.085+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:06:29.119+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.122 seconds
[2024-12-23T06:07:34.190+0700] {processor.py:186} INFO - Started process (PID=3861) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:07:34.192+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:07:34.198+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:07:34.197+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:07:34.242+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:07:34.232+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:07:34.245+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:07:34.244+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:07:34.247+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:07:34.277+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-12-23T06:08:28.762+0700] {processor.py:186} INFO - Started process (PID=4023) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:08:28.764+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:08:28.769+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:08:28.768+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:08:28.817+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:08:28.808+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:08:28.820+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:08:28.819+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:08:28.822+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:08:28.851+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.112 seconds
[2024-12-23T06:08:55.811+0700] {processor.py:186} INFO - Started process (PID=4123) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:08:55.814+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:08:55.819+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:08:55.817+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:08:55.857+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:08:55.849+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:08:55.860+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:08:55.859+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:08:55.862+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:08:55.898+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2024-12-23T06:11:48.905+0700] {processor.py:186} INFO - Started process (PID=4504) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:11:48.908+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:11:48.913+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:11:48.911+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:11:48.952+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:11:48.943+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:11:48.956+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:11:48.955+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:11:48.958+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:11:48.988+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2024-12-23T06:11:53.032+0700] {processor.py:186} INFO - Started process (PID=4518) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:11:53.034+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:11:53.039+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:11:53.038+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:11:53.087+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:11:53.079+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:11:53.090+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:11:53.089+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:11:53.091+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:11:53.119+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2024-12-23T06:13:04.872+0700] {processor.py:186} INFO - Started process (PID=4721) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:13:04.875+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:13:04.879+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:13:04.877+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:13:04.912+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:13:04.906+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:13:04.914+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:13:04.913+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:13:04.916+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:13:04.945+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2024-12-23T06:13:53.121+0700] {processor.py:186} INFO - Started process (PID=4863) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:13:53.124+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:13:53.129+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:13:53.127+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:13:53.175+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:13:53.168+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:13:53.178+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:13:53.177+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:13:53.179+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:13:53.205+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2024-12-23T06:14:41.058+0700] {processor.py:186} INFO - Started process (PID=5003) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:14:41.060+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:14:41.065+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:14:41.063+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:14:41.100+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:14:41.092+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:14:41.103+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:14:41.102+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:14:41.105+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:14:41.131+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.086 seconds
[2024-12-23T06:15:43.317+0700] {processor.py:186} INFO - Started process (PID=5185) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:15:43.320+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:15:43.325+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:15:43.324+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:15:43.381+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:15:43.370+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:15:43.384+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:15:43.382+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:15:43.386+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:15:43.421+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2024-12-23T06:17:23.386+0700] {processor.py:186} INFO - Started process (PID=5438) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:17:23.388+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:17:23.393+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:17:23.391+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:17:23.432+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:17:23.423+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:17:23.435+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:17:23.434+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:17:23.436+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:17:23.466+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-12-23T06:17:37.745+0700] {processor.py:186} INFO - Started process (PID=5485) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:17:37.747+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:17:37.753+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:17:37.751+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:17:37.798+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:17:37.790+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:17:37.801+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:17:37.800+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:17:37.803+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:17:37.830+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-12-23T06:18:53.904+0700] {processor.py:186} INFO - Started process (PID=5691) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:18:53.907+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:18:53.910+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:18:53.909+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:18:53.947+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:18:53.940+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:18:53.951+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:18:53.949+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:18:53.953+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:18:53.984+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-12-23T06:19:04.691+0700] {processor.py:186} INFO - Started process (PID=5728) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:19:04.693+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:19:04.699+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:19:04.697+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:19:04.744+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:19:04.736+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:19:04.747+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:19:04.746+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:19:04.749+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:19:04.775+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2024-12-23T06:20:22.115+0700] {processor.py:186} INFO - Started process (PID=5953) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:20:22.117+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:20:22.122+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:20:22.119+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:20:22.165+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:20:22.155+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:20:22.168+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:20:22.166+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:20:22.170+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:20:22.207+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2024-12-23T06:20:59.521+0700] {processor.py:186} INFO - Started process (PID=6047) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:20:59.524+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:20:59.529+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:20:59.527+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:20:59.581+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:20:59.572+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:20:59.584+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:20:59.583+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:20:59.586+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:20:59.619+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.122 seconds
[2024-12-23T06:22:58.654+0700] {processor.py:186} INFO - Started process (PID=6379) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:22:58.656+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:22:58.662+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:22:58.660+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:22:58.705+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:22:58.698+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:22:58.708+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:22:58.706+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:22:58.709+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:22:58.737+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2024-12-23T06:23:00.376+0700] {processor.py:186} INFO - Started process (PID=6383) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:23:00.378+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:23:00.385+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:23:00.383+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:23:00.431+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:23:00.422+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:23:00.435+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:23:00.433+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:23:00.437+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:23:00.472+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2024-12-23T06:24:19.031+0700] {processor.py:186} INFO - Started process (PID=6637) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:24:19.034+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:24:19.040+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:24:19.038+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:24:19.088+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:24:19.075+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:24:19.091+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:24:19.090+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:24:19.093+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:24:19.144+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.131 seconds
[2024-12-23T06:24:48.538+0700] {processor.py:186} INFO - Started process (PID=6720) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:24:48.540+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:24:48.545+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:24:48.544+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:24:48.587+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:24:48.580+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:24:48.590+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:24:48.588+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:24:48.591+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:24:48.618+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.105 seconds
[2024-12-23T06:25:46.763+0700] {processor.py:186} INFO - Started process (PID=6915) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:25:46.765+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:25:46.770+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:25:46.769+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:25:46.812+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:25:46.803+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:25:46.815+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:25:46.813+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:25:46.816+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:25:46.851+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-12-23T06:26:35.043+0700] {processor.py:186} INFO - Started process (PID=7049) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:26:35.046+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:26:35.054+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:26:35.051+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:26:35.097+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:26:35.089+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:26:35.100+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:26:35.099+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:26:35.102+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:26:35.133+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.111 seconds
[2024-12-23T06:27:20.267+0700] {processor.py:186} INFO - Started process (PID=7183) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:27:20.270+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:27:20.275+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:27:20.273+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:27:20.312+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:27:20.304+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:27:20.314+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:27:20.313+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:27:20.316+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:27:20.357+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-12-23T06:28:22.622+0700] {processor.py:186} INFO - Started process (PID=7364) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:28:22.625+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:28:22.631+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:28:22.629+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:28:22.680+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:28:22.671+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:28:22.683+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:28:22.682+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:28:22.684+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:28:22.712+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2024-12-23T06:28:56.711+0700] {processor.py:186} INFO - Started process (PID=7475) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:28:56.712+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:28:56.717+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:28:56.715+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:28:56.748+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:28:56.742+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:28:56.751+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:28:56.749+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:28:56.753+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:28:56.784+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2024-12-23T06:30:11.059+0700] {processor.py:186} INFO - Started process (PID=7688) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:30:11.062+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:30:11.067+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:30:11.065+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:30:11.106+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:30:11.099+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:30:11.109+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:30:11.108+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:30:11.110+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:30:11.135+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2024-12-23T06:30:24.445+0700] {processor.py:186} INFO - Started process (PID=7742) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:30:24.449+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:30:24.453+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:30:24.452+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:30:24.486+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:30:24.478+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:30:24.489+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:30:24.488+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:30:24.490+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:30:24.519+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
[2024-12-23T06:31:52.731+0700] {processor.py:186} INFO - Started process (PID=7985) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:31:52.733+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:31:52.738+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:31:52.736+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:31:52.778+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:31:52.772+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:31:52.781+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:31:52.780+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:31:52.782+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:31:52.809+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2024-12-23T06:31:55.458+0700] {processor.py:186} INFO - Started process (PID=8004) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:31:55.461+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:31:55.466+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:31:55.464+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:31:55.507+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:31:55.499+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:31:55.510+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:31:55.509+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:31:55.511+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:31:55.544+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-12-23T06:33:32.708+0700] {processor.py:186} INFO - Started process (PID=8295) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:33:32.711+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:33:32.716+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:33:32.714+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:33:32.752+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:33:32.743+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:33:32.756+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:33:32.754+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:33:32.757+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:33:32.786+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2024-12-23T06:33:46.887+0700] {processor.py:186} INFO - Started process (PID=8332) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:33:46.890+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:33:46.895+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:33:46.893+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:33:46.933+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:33:46.924+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:33:46.935+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:33:46.934+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:33:46.936+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:33:46.963+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-12-23T06:35:11.254+0700] {processor.py:186} INFO - Started process (PID=8573) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:35:11.257+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:35:11.262+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:35:11.261+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:35:11.301+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:35:11.295+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:35:11.304+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:35:11.303+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:35:11.306+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:35:11.338+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2024-12-23T06:36:37.983+0700] {processor.py:186} INFO - Started process (PID=8844) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:36:37.985+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:36:37.990+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:36:37.989+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:36:38.034+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:36:38.024+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:36:38.038+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:36:38.036+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:36:38.040+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:36:38.066+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2024-12-23T06:36:56.560+0700] {processor.py:186} INFO - Started process (PID=8894) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:36:56.562+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:36:56.567+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:36:56.566+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:36:56.597+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:36:56.591+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:36:56.601+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:36:56.599+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:36:56.602+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:36:56.632+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.086 seconds
[2024-12-23T06:38:14.811+0700] {processor.py:186} INFO - Started process (PID=9175) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:38:14.814+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:38:14.820+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:38:14.817+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:38:14.855+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:38:14.848+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:38:14.859+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:38:14.857+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:38:14.861+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:38:14.895+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2024-12-23T06:38:39.626+0700] {processor.py:186} INFO - Started process (PID=9255) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:38:39.629+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:38:39.637+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:38:39.635+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:38:39.728+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:38:39.709+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:38:39.736+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:38:39.732+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:38:39.740+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:38:39.797+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.210 seconds
[2024-12-23T06:40:41.167+0700] {processor.py:186} INFO - Started process (PID=9581) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:40:41.170+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:40:41.176+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:40:41.174+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:40:41.228+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:40:41.219+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:40:41.231+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:40:41.230+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:40:41.233+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:40:41.264+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.122 seconds
[2024-12-23T06:42:35.737+0700] {processor.py:186} INFO - Started process (PID=9847) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:42:35.740+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:42:35.744+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:42:35.742+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:42:35.785+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:42:35.777+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:42:35.788+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:42:35.787+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:42:35.790+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:42:35.819+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-12-23T06:44:35.093+0700] {processor.py:186} INFO - Started process (PID=10234) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:44:35.096+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:44:35.102+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:44:35.100+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:44:35.151+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:44:35.142+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:44:35.154+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:44:35.153+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:44:35.155+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:44:35.188+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-12-23T06:46:32.465+0700] {processor.py:186} INFO - Started process (PID=10543) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:46:32.467+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:46:32.472+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:46:32.471+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:46:32.512+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:46:32.506+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:46:32.514+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:46:32.514+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:46:32.516+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:46:32.546+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2024-12-23T06:48:34.882+0700] {processor.py:186} INFO - Started process (PID=10792) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:48:34.885+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:48:34.890+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:48:34.888+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:48:34.931+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:48:34.924+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:48:34.934+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:48:34.933+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:48:34.936+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:48:34.960+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-12-23T06:50:36.822+0700] {processor.py:186} INFO - Started process (PID=11031) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:50:36.825+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:50:36.830+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:50:36.828+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:50:36.889+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:50:36.879+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:50:36.893+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:50:36.891+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:50:36.895+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:50:36.927+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2024-12-23T06:52:48.430+0700] {processor.py:186} INFO - Started process (PID=11289) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:52:48.432+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:52:48.438+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:52:48.436+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:52:48.479+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:52:48.472+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:52:48.482+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:52:48.481+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:52:48.483+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:52:48.514+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.105 seconds
[2024-12-23T06:54:44.086+0700] {processor.py:186} INFO - Started process (PID=11516) to work on /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:54:44.089+0700] {processor.py:914} INFO - Processing file /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-23T06:54:44.093+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:54:44.092+0700] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:54:44.142+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:54:44.134+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-23T06:54:44.145+0700] {logging_mixin.py:190} INFO - [2024-12-23T06:54:44.144+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-23T06:54:44.147+0700] {processor.py:927} WARNING - No viable dags retrieved from /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-23T06:54:44.177+0700] {processor.py:208} INFO - Processing /mnt/d/Project/airflow-news/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
